---

- copy:
    dest: /etc/yum.repos.d/nginx.repo
    content: |
      [nginx-stable]
      name=nginx stable repo
      baseurl=http://nginx.org/packages/centos/$releasever/$basearch/
      gpgcheck=1
      enabled=1
      gpgkey=https://nginx.org/keys/nginx_signing.key
      module_hotfixes=true

- yum:
    name: nginx
    state: latest
    enablerepo: nginx-stable
