---

- name: "install : https transport and privacy guard tools"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - apt-transport-https
      - gnupg2
      - ca-certificates

- name: "Import : repo.key"
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
  register: nginx_repo_key

- name: "configure : repository"
  apt_repository:
    repo: "deb http://nginx.org/packages/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx"
    filename: nginx
  register: nginx_repo

- name: install nginx
  apt:
    name:
      - nginx
    update_cache: "{% if nginx_repo is changed or nginx_repo_key is changed %}yes{% else %}no{% endif %}"
    state: "{{ pkg_state }}"
