---
# tasks file for egeneralov.nginx

- name: Import repo key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
  register: nginx_repo_key

- name: Add official repository
  apt_repository:
    repo: "deb http://nginx.org/packages/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx"
  register: nginx_repo

- name: update apt cache
  apt:
    update_cache: yes
  when: nginx_repo is changed or nginx_repo_key is changed

- name: install nginx
  apt:
    name: nginx
    state: present

- name: purge default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  register: nginx_default_conf

- name: ensure nginx is running and autostart enabled for it
  systemd:
    name: nginx
    state: "{% if nginx_default_conf is changed %}re{% endif %}started"
    enabled: yes

- name: nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  register: nginx_nginx_conf

- name: place vhosts
  template:
    src: vhost.conf.j2
    dest: "/etc/nginx/conf.d/{{ item.domain }}.conf"
  with_items: "{{ vhosts }}"
  register: nginx_vhosts_conf

- name: reload nginx on config changes
  systemd:
    name: nginx
    state: reloaded
  when: nginx_nginx_conf is changed or nginx_vhosts_conf is changed

- name: "iptables: nginx"
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
    comment: nginx
  with_items:
    - 80
    - 443
  when: manage_iptables
