---
# tasks file for egeneralov.nginx

- include_tasks: "{{ ansible_facts['distribution'] }}.yml"

- name: "remove : default.conf"
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  register: nginx_default_conf

- name: "systemd : nginx"
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: "iptables : nginx input 80 443"
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
    comment: nginx
  with_items:
    - 80
    - 443
  when: manage_iptables

- include_tasks: exporter.yml

- name: "configure : upstreams"
  template:
    src: "upstream.conf.j2"
    dest: "/etc/nginx/conf.d/upstream-{{ item.key }}.conf"
    backup: yes
  register: nginx_nginx_conf
  with_dict: "{{ upstreams }}"

- name: "configure : nginx.conf"
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    validate: "nginx -t -c %s"
    backup: yes
  register: nginx_nginx_conf

- name: "configure : vhosts"
  template:
    src: "vhost.conf.j2"
    dest: "/etc/nginx/conf.d/{{ item.domain }}.conf"
    backup: yes
  with_items: "{{ vhosts }}"
  register: nginx_vhosts_conf

- name: "systemd : reload nginx"
  systemd:
    name: nginx
    state: "{% if nginx_nginx_conf is changed or nginx_vhosts_conf is changed or nginx_default_conf is changed %}reloaded{% else %}started{% endif %}"
